version: 2.1

executors:
  clojure:
    docker:
      - image: circleci/clojure:lein-2.9.3

workflows:
  version: 2
  ci:
    jobs:
      - test

jobs:
  test:
    executor: clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "project.clj" }}
            - v1-deps
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-deps-{{ checksum "project.clj" }}
      - run: lein test
